force-app/main/default/objects/setupFields__mdt/setupFields__mdt.object-meta.xml
<CustomObject>
    <label>configuración campos</label>
    <pluralLabel>configuración campos</pluralLabel>
</CustomObject>

force-app/main/default/objects/setupFields__mdt/fields/Lista_de_campos__c.field-meta.xml
<CustomField>
    <fullName>Lista_de_campos__c</fullName>
    <label>Lista de campos</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/classes/FieldsByActionController.cls
public with sharing class FieldsByActionController {
    
    @AuraEnabled(Cacheable = true)
    public static string fieldByActionCode (String actionCode){
        try {
            setupFields__mdt currentActionCode = [SELECT Lista_de_campos__c
                                                                FROM setupFields__mdt
                                                                WHERE DeveloperName =: actionCode];
            return currentActionCode.Lista_de_campos__c;
        } catch (Exception e) {
            throw new AuraHandledException(e.getMessage());
        }
    }


}